server:
  port: 8003
  ssl:
    bundle: messages-resource
    client-auth: need

spring:
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  application:
    name: inyaa-resource # 应用名称
  profiles:
    active: dev # 指定环境，默认加载 default 环境
  cloud:
    consul:
      # Consul 服务器地址
      host: 43.143.123.82
      port: 8500
      # 配置中心相关配置
      config:
        # 是否启用配置中心，默认值 true 开启
        enabled: true
        # 指定配置格式为 yaml
        format: YAML
        watch:
          # 是否开启自动刷新，默认值 true 开启
          enabled: true
          # 刷新频率，单位：毫秒，默认值 1000
          delay: 1000
      # 服务发现相关配置
      discovery:
        register: true                                # 是否需要注册
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}} # 注册实例 id（必须唯一）
        service-name: ${spring.application.name}      # 服务名称
        port: ${server.port}                          # 服务端口
        prefer-ip-address: true                       # 是否使用 ip 地址注册
        # ip-address: ${spring.cloud.client.ip-address} # 服务请求 ip
  ssl:
    bundle:
      jks:
        messages-resource:
          key:
            alias: messages-resource-sample
            password: password
          keystore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9002/oauth2/jwks
  data:
    redis:
      # 连接地址
      host: 43.143.123.82
      # 端口
      port: 6379
      # 数据库
      database: 0
      # 用户名，如果有
      # username:
      # 密码，如果有
      password: yuxiaohao